### ISSUE TITLE
Module Migration Does Not Handle Negating Imported Variables

### ISSUE THREAD

**Issue by justinryder** [sass/migrator#114]
**Reduced Test Case**

Given the following files:

`_variables.scss`:
```scss
$foo: 1;
```

`styles.scss`:
```scss
@import 'variables';

.foo {
    padding: -$foo;
}
```

Run the following command (sass-migrator@1.0.0):
`sass-migrator module styles.scss`

**Actual Results**

The resulting `styles.scss` throws a compilation error where the module is used.

```
@use 'variables';

.foo {
    padding: -variables.$foo;
}
```

Compilation error (sass@1.23.0):
```
> npx sass styles.scss
Error: There is no module with the namespace "-variables".
  ╷
4 │     padding: -variables.$foo;
  │              ^^^^^^^^^^^^^^^
  ╵
  styles.scss 4:14  root stylesheet
```

**Expected Results**

`styles.scss` should be migrated with no compilation errors.

Possible valid target output (this compiles successfully with sass@1.23.0):
```
@use 'variables';

.foo {
    padding: -(variables.$foo);
}
```

**Comment by jathak** [comment]
@nex3: What would be the better style for migrating these cases?
With parentheses around the namespaced variable or with a space after the `-`?

**Comment by nex3** [comment]
We could consider parsing initial hyphens before `IDENTIFIER "."` as negations—it requires some amount of lookahead in the parser, but that's par for the course in Sass :laughing:. I'll add it to the design meeting agenda.

For now, it's probably best to just generate parentheses here.
