### ISSUE TITLE
Stylelint support

### ISSUE THREAD

**Issue by selcet** [sass/migrator#116]
Have troubles with configing Stylelint thought .stylelintrc, adding support of custom rule:
```
{
  "extends": "stylelint-config-standard",
  "rules": {
   ...
     "at-rule-no-unknown": [ true, {
        "ignoreAtRules": ["use"]
      }],
   ...
  }
}
```
But, even after such config have [error in file](https://user-images.githubusercontent.com/6522667/66704943-6ffffc00-ed29-11e9-9579-73b3669befd2.png).
![Screen+Shot+2019-10-12+19-48-22](https://user-images.githubusercontent.com/6522667/66704943-6ffffc00-ed29-11e9-9579-73b3669befd2.png)

**Comment by jathak** [comment]
This looks like an issue with Stylelint, rather than an issue with Sass itself or this migrator. You should [file an issue](https://github.com/stylelint/stylelint/issues/new/choose) there.
