### ISSUE TITLE
Better support for migrating libraries

### ISSUE THREAD

**Issue by jathak** [sass/migrator#15]
This has two parts:

- [x] Unprefix members when migrating a library to the module system (#21)
- [ ] Migrate stylesheets with dependencies that are already migrated, including unprefixing if necessary (#22)

Original issue:
* * *

Right now, the migrator pretty much assumes that the entrypoint(s) and all dependencies will be migrated together, which only really works when all stylesheets are local to one project. The migrator should have a mode designed for migrating libraries without breaking anything downstream.

This should support the following:

- When migrating `library.scss`, the migrator should also create a `library.import.scss` file that maintains the pre-migration behavior but warns when imported.
- If a library previously explicitly namespaced its members with a prefix (e.g. `lib-foo`), the migrator should be able to automatically remove the prefixes and instead rely on the module namespace (e.g. `library.foo`)
- When migrating a stylesheet that depends on a previously migrated library, the migrator should be able to remove those prefixes, ideally without the user having to explicitly specify the prefixes to be removed.

**Comment by jathak** [comment]
One example for how this might work:

Original `library.scss`:
```scss
$lib-background: blue;
$lib-foreground: yellow;
```

Running migrator with `module_migrator library.scss --unprefix 'lib-'` should result in:

Migrated `library.scss`:
```scss
$background: blue;
$foreground: yellow;
```

Generated `library.import.scss`:
```scss
$_prefix: "lib-";
@warn "You are importing a library that has been migrated to @use.";
$lib-background: blue;
$lib-foreground: yellow;
```
<hr/>

Now, if that `entrypoint.scss` depends on this library
```scss
@import "library";
a {
  background-color: $lib-background;
  color: $lib-foreground;
}
```

and the user runs the migrator, it should be able to detect the prefix automatically by looking at the `$_prefix` variable in `library.import.scss`, resulting in:
```scss
@use "library";
a {
  background-color: $library.background;
  color: $library.foreground;
}

**Comment by jathak** [comment]
@nex3, thoughts on this?

**Comment by nex3** [comment]
Generally, this sounds good. I think I wouldn't add the warning on import, since I expect most library authors won't care that much if their downstream users are using `@use` and thus may not want the warning cluttering up the UX.

You can also generate a much simpler `library.import.scss` by forwarding `library.scss` with a prefix:

```scss
@forward "library" as lib-*;
```

That way you won't have to duplicate all the definitions.
