### ISSUE TITLE
Sass Migrator file name incorrect on Windows

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [sass/migrator#181]
The version of Sass Migrator currently on Chocolatey has an error.

Cannot find file at '..\lib\sass-migrator\tools\sass_migrator.bat' (C:\ProgramData\chocolatey\lib\sass-migrator\tools\sass_migrator.bat)

That's because the correct file name is "sass-migrator.bat," with a hyphen.

Thank you!!!

**Comment by jathak** [comment]
See #222.
