### ISSUE TITLE
Unexpected replacement for division operator

### ISSUE THREAD

**Issue by CaelanStewart** [sass/migrator#187]
Hi,

I've just followed this page: https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration

Perhaps it's documented somewhere tucked away, but I've just used the sass-migrator against a SCSS codebase, and it replaced all instances of the division operator with an undefined function named 'divide'.

It changed this:

```
margin-top: $gap / 4;
```

To this:

```
margin-top: divide($gap, 4);
```

If this is intentional, it might be best to update the documentation copy here:

> You can use the Sass migrator to automatically update your stylesheets to use **math.div() and list.slash().**

It's fine, I can just define a wrapper function or search and replace `divide(` with `math.div(` and add the `@use` statement. But it was unexpected.

**Comment by ccambournac** [comment]
Experienced the same issue after migration :
```
SassError: Undefined operation "divide(505px, 450px) * 100%".
   ╷
29 │             padding-top: divide(505px, 450px) * 100%;
   │                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  styles/components/landing.scss 29:17  @import
  styles/global/app.scss 21:9           root stylesheet
```

Had to manually add `@use 'sass:math';` to app.scss file and to find/replace all `divide()` by `math.div()`.

**Comment by jathak** [comment]
Whoops. We forgot to release the proper version of the division migrator. If you upgrade to the latest version (1.4.0), it should now properly migrate to `math.div` and add a `@use 'sass:math'` rule.

Sorry for the trouble!
