### ISSUE TITLE
Error: Could not find Sass file at 'C:\...\*.scss'. Migration failed!

### ISSUE THREAD

**Issue by frattaro** [sass/migrator#190]
After installing sass-migrator via Chocolatey on windows 10, bypassing the bat filename error (#181) by running:

PS c:\my_code_dir> `dir -recurse -include *.scss | %{c:\programdata\chocolatey\lib\sass-migrator\tools\sass-migrator.bat division ($_.FullName.substring(0, $_.FullName.length - $_.Name.length)+"*.scss")}`

I get:
```
Error: Could not find Sass file at 'C:\.my_code_dir\..\*.scss'.
Migration failed!
```
Tried pointing directly at the file, or just pointing to the directory, or leaving the wildcard+extension absent, a la:

PS c:\my_code_dir> `dir -recurse -include *.scss | %{c:\programdata\chocolatey\lib\sass-migrator\tools\sass-migrator.bat division $_.FullName}`

PS c:\my_code_dir> `dir -recurse -include *.scss | %{c:\programdata\chocolatey\lib\sass-migrator\tools\sass-migrator.bat division $_.FullName.substring(0, $_.FullName.length - $_.Name.length)}`

PS c:\my_code_dir> `dir -recurse -include *.scss | %{c:\programdata\chocolatey\lib\sass-migrator\tools\sass-migrator.bat division ($_.FullName.substring(0, $_.FullName.length - $_.Name.length)+"*")}`

but same error.

**Comment by jathak** [comment]
When running it from Chocolatey, does `<path to migrator bat> division **/*.scss` work?

Dart's `glob` package only supports POSIX-style paths, so `\*` is interpreted a literal asterisk, rather than a path separator followed by a wildcard.

**Comment by jathak** [comment]
Actually, wait. The Chocolatey version is out of date (we haven't been able to publish new versions of it for a while). Can you try with the [standalone release](https://github.com/sass/migrator/releases/latest)?

**Comment by frattaro** [comment]
Yes -- standalone release worked (second one) via windows cmd with:

```
C:\my_code_dir>c:\users\afrattar\desktop\sass-migrator-1.4.0-windows-x64\sass-migrator\sass-migrator.bat division **/*
Error: Could not find Sass file at '.\.cache\.eslintrc.json'.
Migration failed!

C:\my_code_dir>c:\users\afrattar\desktop\sass-migrator-1.4.0-windows-x64\sass-migrator\sass-migrator.bat division **/*.scss
```

Thanks much

**Comment by frattaro** [comment]
btw, the only thing i've ever needed chocolatey for is to install ruby so i could use their gem to get an .npmrc into a travis-ci secret. I can't imagine it's a huge loss :)
