### ISSUE TITLE
sass-migrator: command not found

### ISSUE THREAD

**Issue by federicavecchi22** [sass/migrator#195]
Project Laravel 8

in package.json

devDependencies{
    "sass": "^1.34.0",
    "sass-loader": "^8.0.0",
    "sass-migrator": "^1.4.3",
}

run `npm run dev`

> dev
> npm run development

> development
> mix

● Mix █████████████████████████ building (10%) 0/3 entries 216/259 dependencies 3/207 modules 85 active 
 node_modules/bootstrap-vue/esm/components/toast/helpers/bv-toast.js

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 302:31  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 8:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

run `npm install sass-migrator` 

the installation is correctly done , but it gives me the code below.
run `sass-migrator division **/*.scss`

return:
`-bash: sass-migrator: command not found`

**Comment by jathak** [comment]
`npm install sass-migrator` installs a package in a local directory, but doesn't make any binaries available on your path. You need to run `npm install -g sass-migrator` as specified in the documentation (depending on how you installed Node, you may need root access to do this).

Another alternative is to use `npx` to run the package from the local installation (e.g. `npx sass-migrator division **/*.scss`)
