### ISSUE TITLE
Issue with "glob" - It's not clear which file to import. 

### ISSUE THREAD

**Issue by Hirbod** [sass/migrator#200]
When I run

`sass-migrator division ./src/**/*.scss`

I get 

```
It's not clear which file to import. Found:
  src/components/content/accordion/_accordion.scss
  src/components/content/accordion/accordion.scss
....
    at /usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:18833:46 {
  dartException: "It's not clear which file to import. Found:\n" +
    '  src/components/content/accordion/_accordion.scss\n' +
    '  src/components/content/accordion/accordion.scss'
}
```

I can bypass this with

`sass-migrator division ./src/**/_*.scss` for fixing files beginning with _ but not the other way around.
I tried to somehow add some regexp but to no success.

I can't remove nor rename these files, since they are needed as is for my specific setup.

**Comment by jathak** [comment]
Having two files with the same name, but one is a partial and the other is not, is not allowed by the Sass language spec (see [here](https://github.com/sass/sass/blob/master/spec/modules.md#resolving-a-file-url-for-partials)), so this error is expected.

**Comment by Hirbod** [comment]
Thanks for clarification. I'll work something out!
