### ISSUE TITLE
sass-migration cannot find file on Windows 10 / Powershell 7 when referenced by full path

### ISSUE THREAD

**Issue by jkesseler** [sass/migrator#214]
When running `sass-migration <migration> <Drive:\full\path\to\file.scss>` an error is shown:
"Error: Could not find Sass file at <Drive:\full\path\to\file.scss>"
When referencing that same file just by name in the same directory the file found.

OS: Windows 10 
Shell: PowerShell 7.2
sass-migratior: Version: 1.5.2 compiled with dart2js 2.13.4

![mage](https://i.imgur.com/t2axvK9.png)

**Comment by jathak** [comment]
How did you install the migrator? If you installed via npm, could you try [downloading the standalone version](https://github.com/sass/migrator/releases/latest) and seeing if you get the same error?

**Comment by take5v** [comment]
Same issue. Tried both with the latest migrator from npm and when debugging from source.

**Comment by stof** [comment]
I think this might have been fixed by https://github.com/sass/migrator/pull/239 (released in version 1.7.3 of the migrator)
