### ISSUE TITLE
Invalid warnings when --migrate-deps is used on a file with built-in @use rules

### ISSUE THREAD

**Issue by jamacoe** [sass/migrator#230]
I'm trying to migrate/update a template with the following code (on Windows 10 using latest dart.exe):
```
main.scss:
  ...
  @import 'libs/functions';
  ...

libs/_functions.scss:
  /// @author Someone
  /// @param {list} $list List.
  /// @param {integer} $index Index.
  /// @return {list} Updated list.
  ...
  /// @author Someone
  /// @param {map} $map Map.
  /// @param {string} $keys Key(s).
  /// @return {string} Value.
  ...

`sass-migrator --migrate-deps --verbose module main.scss` changes the first file to:

main.scss:
  @use 'libs/functions';
```
and prepends the following lines to:
```
libs/_functions.scss:
  @use "sass:list";
  @use "sass:map";
  @use "sass:math";
  @use "sass:meta";
  @use "sass:string";
  @use "vars";
```
When trying to run again in order to change the outdated division usage `/` :
```
`sass-migrator --migrate-deps --verbose division main.scss`:
```
I receive the following error messages:
```
WARNING on line 1, column 1 of main.scss: Could not find Sass file at 'sass:meta'.
  ╷
1 │ @use "sass:meta";
  │ ^^^^^^^^^^^^^^^^
  ╵
WARNING on line 1, column 1 of libs\_functions.scss: Could not find Sass file at 'sass:list'.
  ╷
1 │ @use "sass:list";
  │ ^^^^^^^^^^^^^^^^
  ╵
WARNING on line 2, column 1 of libs\_functions.scss: Could not find Sass file at 'sass:map'.
  ╷
2 │ @use "sass:map";
  │ ^^^^^^^^^^^^^^^
  ╵
WARNING on line 3, column 1 of libs\_functions.scss: Could not find Sass file at 'sass:math'.
  ╷
3 │ @use "sass:math";
  │ ^^^^^^^^^^^^^^^^
  ╵
WARNING on line 5, column 1 of libs\_functions.scss: Could not find Sass file at 'sass:string'.
  ╷
5 │ @use "sass:string";
  │ ^^^^^^^^^^^^^^^^^^
  ╵
Nothing to migrate!
```
So, first of all I get these warnings/error messages. **Is that ok or a bug?** Second, it did't migrate the divisions and all the `division outside of calc()` errors still get reported, when compiling with `sass`. And as a third problem, I'm looking for a switch to change all `@elseif` to `@else if` as well as delete unneeded `!global `flags. Did that manually now in all files.

**Comment by jathak** [comment]
Those warnings are indeed a bug, but I'm not able to reproduce the issue you're having with division not actually being migrated. I'll target this bug for your first issue. Can you file another bug for your other issue, including a minimal reproduction?
