### ISSUE TITLE
sass-migration cannot find files containing `#`

### ISSUE THREAD

**Issue by mkusaka** [sass/migrator#237]
Currently, sass-migration cannot find files containing `#`.
Reproduction environment is Mac (M1).

## How to reproduce
We have prepared a repository for reproduction
https://github.com/mkusaka/sass-migrator-glob-issue-repro

1. clone the repository
2. yarn reproduce (internally, run `sass-migrator division "src/#styles/style.scss"`)

## actual
Get an error message as follows
```
❯ yarn reproduce
yarn run v1.22.19
$ sass-migrator division "src/#styles/style.scss"
Error: Could not find Sass file at 'src/#styles/style.scss'.
Migration failed!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But the file actually exists

## expected
Be able to find the file in question, as if it did not contain `#`.
```
$ sass-migrator division "src/styles/style.scss"
Nothing to migrate!
```

**Comment by jathak** [comment]
The issue here is probably that we're parsing file paths passed on the command line as URLs, so the `#` get's treated as a fragment, rather than part of the filename. I'll take a look.
