### ISSUE TITLE
Error "Error: Could not find Sass file at '*'." when using Angular "stylePreprocessorOptions.includePaths"

### ISSUE THREAD

**Issue by bgpedersen** [sass/migrator#246]
After running `npx sass-migrator module src/styles.scss --migrate-deps --load-path=node_modules` getting error:

```bash
> npx sass-migrator module src/styles.scss --migrate-deps --load-path=node_modules
Error: Could not find Sass file at 'breakpoints'.
   ╷
12 │ @import 'breakpoints';
   │         ^^^^^^^^^^^^^
   ╵
  src\styles.scss 12:9  root stylesheet
Migration failed!
```

In Angular in angular.json configuration file, we can set `includePaths` option, so instead of specifying the relative path for a scss file import in all our scss files, we can just specify the `includePath` for where it should look, and simply import like `@import 'breakpoints';`.

```json
"stylePreprocessorOptions": {
  "includePaths": [
    "src",
    "src/content/scss/defaults",
    "src/content/scss/components",
    "src/content/scss/utilities"
  ]
},
```

That would mean, that in order to use the migration tool, we have to manually go through hundreds of scss files and change the import to relative paths, for where that particular file is located.

Can this migration tool take into consideration of the specified `includePaths` ?

- https://angular.io/guide/workspace-config#style-preprocessor-options

**Comment by nex3** [comment]
You can specify [`--load-path` for the migrator CLI](https://sass-lang.com/documentation/cli/migrator/#load-path) if you want it to search specific paths. If you want to automatically pass load paths from your Angular configuration to the migrator, that's probably something best left up to Angular's Sass integration.

**Comment by bgpedersen** [comment]
@nex3 Hi, thanks for the answer. Maybe i'm misunderstanding you, so bear with me:

As you can see in my description, i'm already using the `load-path` option, but it is only being used for `node_modules`, to avoid migrate styles imported from there (third parties, as described in your migration tool `Dependencies loaded from load paths are assumed to be third-party libraries, so the migrator will not migrate them even when the [--migrate-deps option](https://sass-lang.com/documentation/cli/migrator/#migrate-deps) is passed.`), so this option would not work when i want `migrate-deps` to work for my own files.

What do you think?

Dependencies loaded from load paths are assumed to be third-party libraries, so the migrator will not migrate them even when the [--migrate-deps option](https://sass-lang.com/documentation/cli/migrator/#migrate-deps) is passed.

**Comment by nex3** [comment]
The `stylePreprocessorOptions.includePaths` setting seems to be setting the same option as `--load-paths`. If you want to match that behavior, you'll have to pass `--load-paths` as well and either separately migrate the dependencies that are loaded that way or pass `--migrate-deps` to migrate _all_ dependencies.
