### ISSUE TITLE
Issue with absolute @import when running migrations

### ISSUE THREAD

**Issue by balteo** [sass/migrator#257]
**sass-migrator version**
 2.0.3 compiled with dart2js 3.3.1

**sass version**
 ^1.56.2

## Issue

It seems that the **sass-migrator** does not handle absolute `@import` 

I am trying to migrate scss stylesheets of an angular 17 application as follows:

`sass-migrator --migrate-deps  module  src/styles/main.scss`

I get errors such as:

```
Error: Could not find Sass file at 'theme'.
  ╷
1 │ @import 'theme';
  │         ^^^^^^^
  ╵
  src/styles/utils/_site-variables.scss 1:9  root stylesheet
Migration failed!
```

Here is my directory structure:
```
src/styles
├── base
│   ├── _base.scss
│   └── _reset.scss
├── layout
│   ├── _header.scss
│   ├── _main.scss
│   ├── _overlay.scss
│   ├── _position.scss
│   └── _product.scss
├── main.scss
├── module
│   ├── _action.scss
│   ├── _button.scss
│   ├── _card.scss
│   ├── _chart.scss
│   ├── _dialog.scss
│   ├── _icons.scss
│   ├── _input.scss
│   ├── _product.scss
│   ├── _select.scss
│   ├── _table.scss
│   └── _title.scss
├── theming
│   ├── das-gmvet
│   │   ├── _theme.scss
│   │   └── material.scss
│   ├── default
│   │   ├── _theme.scss
│   │   └── material.scss
│   ├── srs-myvete
│   │   ├── _theme.scss
│   │   └── material.scss
│   └── srs-vetmanager
│       ├── _theme.scss
│       └── material.scss
└── utils
    ├── _all.scss
    ├── _functions.scss
    ├── _mixins.scss
    └── _site-variables.scss
```

In the case above, angular can find the `src/styles/theming/default/_theme.scss` stylesheet because it is referred to in the `angular.json` config file as a style preprocessor option (see below) but the sass-migrator cannot.

```
"stylePreprocessorOptions": {
 "includePaths": ["src/styles/theming/default"]
}
```

If I specify the relative path as follows in the `_site-variables.scss` file, I get other errors such as:

```
Error: Could not find Sass file at 'styles/utils/site-variables'.
  ╷
1 │ @import 'styles/utils/site-variables';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/styles/base/_base.scss 1:9  root stylesheet
Migration failed!
```

This is because of the absolute `@import` in `_base.scss`:
`@import 'styles/utils/site-variables';`

Is there any other configuration option or workaround that could help perform the migration?

I noticed that other people have faced the same issue with sass-migrator. See this SO post for instance: https://stackoverflow.com/q/69726775/536299 that might be related.

**Comment by nex3** [comment]
You need to use the [`--load-path` flag](https://sass-lang.com/documentation/cli/migrator/#load-path) to tell the migrator where your load path is, the same as you're passing to Sass through Angular.

**Comment by balteo** [comment]
Hi @nex3 

Thanks for your comment. What is the syntax I need to use for the `--load-path` flag?

I have tried this:

`sass-migrator --migrate-deps  module  src/styles/main.scss --load-path=src/styles/theming/default --load-path=src/styles --load-path=src/styles/utils
`

I still get the following error:

```
Error: Could not find Sass file at 'styles/utils/site-variables'.
  ╷
1 │ @import 'styles/utils/site-variables';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/styles/base/_base.scss 1:9  root stylesheet
Migration failed!
```

**Comment by nex3** [comment]
See the [documentation for load paths](https://sass-lang.com/documentation/at-rules/use/#load-paths). URLs are resolved relative to the load path, so if you want to load `src/styles/utils/site-variables.scss` from the URL `styles/utils/site-variables`, you would pass `--load-path=src`.

**Comment by xianshenglu** [comment]
> See the [documentation for load paths](https://sass-lang.com/documentation/at-rules/use/#load-paths). URLs are resolved relative to the load path, so if you want to load `src/styles/utils/site-variables.scss` from the URL `styles/utils/site-variables`, you would pass `--load-path=src`.

Thanks. I tried it with `sass-migrator module --load-path=/absolute-path/to/angular-project  --migrate-deps src/styles.scss` to make it work with Angular@19.
