### ISSUE TITLE
Migration with Angular Material fails

### ISSUE THREAD

**Issue by leomayer** [sass/migrator#266]
We are developing with Angular Material. As mentioned one should run the migration when using `@import`, which fails. Therefore I randomly picked one file for migration `theme.scss` with the following code:

```
@use '@angular/material' as mat;
@use 'sass:map';
@import 'theme_color_paletts.scss';

//  https://material.angular.io/guide/theming#applying-a-theme-to-components
$light-theme: mat.m2-define-light-theme(
	(
		color: (
			primary: $primaryPalette,
			accent: $accentPalette,
		),
		typography: $app-typography,
		density: $app-density,
	)
);

@include mat.core();
...
```

When I run the command like

```
 node_modules/.bin/sass-migrator --verbose --load-path path/to/my/global/styles --load-path . module src/styles-global/theme.scss        
```

I get the following error

```
Error: Could not find Sass file at '@angular/material'.
  ╷
3 │ @use '@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/styles-global/theme.scss 3:1  root stylesheet
Migration failed!
```

How to include the Material files? Where to find them and how to specify? Or doesn't it work as soon as `@use` appear?

**Comment by nex3** [comment]
If `@angular/material` is installed in `node_modules`, you'll need to pass that as a `--load-path` as well.

**Comment by leomayer** [comment]
@nex3 I have no clue how this should be done. Namely adding 

```
--load-path ./node_modules/@angular/material
```

won't change anything. The error remains the same.

Just for clarifications and confirmation: it is for `scss` files?

**Comment by nex3** [comment]
`--load-path` indicates a path *relative to which* Sass will try to resolve loads. So if you write `@import "@angular/material"`, you don't want to resolve it relative to `node_modules/@angular/material` because that will give you `node_modules/@angular/material/@angular/material`. Instead, you should pass `--load-path node_modules` so that it resolves it relative to the `node_modules` directory itself.

**Comment by leomayer** [comment]
Thx for your detailed explanation. Right now I have the following - working - migration of one file

```
node_modules/.bin/sass-migrator -I ./src/styles-global -I node_modules module src/styles-global/theme.scss;
node_modules/.bin/sass-migrator -I ./src/styles-global -I node_modules module src/app/component/mycomponent/sub-comp1/sub-comp1.scss
```
With setup the `scss` file as default option for our style-files. We have more than one file. Right now I don't see a way to migrate all of them at once - or at least in few chunks. Is there a "simple" way to migrate

* all the files from `src/app`?
* all the files from `src/styles-global`? 

The first would be awesome, for the second I have to confess there are multiple dependencies within but would be even more awesome (?`awesummer` 😉 )

**Comment by nex3** [comment]
You can migrate multiple files either by [passing multiple files on the command line](https://sass-lang.com/documentation/cli/migrator/#usage) or by passing [the `--migrate-deps` flag](https://sass-lang.com/documentation/cli/migrator/#migrate-deps) to migrate all dependencies of a single entrypoint file.

**Comment by leomayer** [comment]
I've created a manual bash script which does the clean up in my complete project structure. I've done something like
```
find . -name "*.scss" -type f -exec grep -q "@import" {} \; -print0 | xargs -0 -I {} sh -c '../node_modules/.bin/sass-migrator -I ./styles-global -I ../node_modules module -d {}'  
```
this did the job. One needs to take care about the proper path, but that granted it works.
