### ISSUE TITLE
Consistently order @uses

### ISSUE THREAD

**Issue by nex3** [sass/migrator#46]
The module migrator currently creates `@use` rules in the order that their members are used, which ends up looking kind of messy. It would be good at some point to produce a more principled ordering. I propose:

* `sass:` `@use`s, in alphabetical order.
* Any `@use`s that come from load paths, in alphabetical order.
* Relative `@use`s, in alphabetical order.
* A newline.
* Same order for `@forward`s as above.
* A newline if there were any `@forward`s.

**Comment by jathak** [comment]
Where do the existing `@import` rules (that get converted to `@use` rules) go in this ordering? I don't think we can reorder the existing ones, since the order of the CSS they emit might matter.

**Comment by nex3** [comment]
Hmm, good point. I suppose after `sass:` `@use`s but before everything else—that way the first loads will happen in the same order as before the migrator, and all future `@use`s will re-use those modules without re-running side effects or changing the CSS order.

**Comment by jathak** [comment]
How should this interact with #88? Should `@forward`s that replace `@import`s be grouped with the other existing `@import`s that are now `@use`s (preserving the CSS load order), or should they go with the other `@forward`s?

**Comment by nex3** [comment]
The former, I think—we should prioritize preserving the compilation behavior over producing stylistically-ideal output.
