### ISSUE TITLE
Update syntax for namespaced variables

### ISSUE THREAD

**Issue by jathak** [sass/migrator#75]
`$namespace.variable` -> `namespace.$variable`

**Comment by kushthedude** [comment]
Hello @jathak , I am new to the community,Can I work on it @jathak ?

**Comment by jathak** [comment]
I'm currently working on both this and #48, but you're welcome to work on any of the other issues.

Make sure to read [CONTRIBUTING.md](https://github.com/sass/migrator/blob/master/CONTRIBUTING.md) if you haven't already.
