### ISSUE TITLE
--remove-prefix can generate invalid private member accesses

### ISSUE THREAD

**Issue by nex3** [sass/migrator#84]
If you remove a prefix that's followed by a `-` in a member name, the migrator won't detect the new member as private and will accordingly generate invalid member references. For example, with `--remove-prefix=a`, `$a-b` will become `module.$-b`, which is invalid.

This seems like a likely thing for users to do by accident if they don't realize that they're supposed to include the trailing `-` in the prefix.

**Comment by jathak** [comment]
Can you think of any valid case where the prefix would not end with a `-` or should the migrator just error if the prefix doesn't end with `-`?

**Comment by nex3** [comment]
I could imagine someone using camel-case identifiers or something weird like that, although that's definitely an edge case. If we *do* assume all prefixes are supposed to end with `-`, it would probably be better to treat `--remove-prefix=a` as equivalent to `--remove-prefix=a-` rather than erroring out.
