### ISSUE TITLE
Use the original URL if it was resolved relative to a load path

### ISSUE THREAD

**Issue by jathak** [sass/migrator#90]
#77 did this for URLs loaded with `NodeModulesImporter`, but we should do the same for load paths

**Comment by nex3** [comment]
Looking deeper at the code here, I'm not sure this is as necessary as it looked originally. We're already re-using the original URLs when migrating existing `@import` rules, so this only comes up when generating `@use` or `@forward` rules from scratch, in which case it makes sense to just choose the shorter option.
